name: Run Serenity BDD with Selenoid

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunSerenityTests
    displayName: 'Run Serenity BDD with Selenoid'
    steps:
      - task: UseJavaVersion@1
        inputs:
          versionSpec: '11'
          addToPath: true

      - checkout: self

      - script: |
          ./gradlew clean test aggregate
          chmod -R 755 ./target/site/serenity

        displayName: 'Run Serenity BDD and Change Permissions'

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'serenity-reports'
          targetPath: $(Build.ArtifactStagingDirectory)