name: Run Serenity BDD with Selenoid

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunSerenityTests
    displayName: 'Run Serenity BDD with Selenoid'
    steps:
      - checkout: self

      - script: |
          export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
          export PATH=$JAVA_HOME/bin:$PATH
          ./gradlew clean test aggregate
          chmod -R 755 ./target/site/serenity

        displayName: 'Run Serenity BDD and Change Permissions'

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'serenity-reports'
          targetPath: $(Build.ArtifactStagingDirectory)