trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunTests
    displayName: 'Run Serenity BDD Tests'
    steps:
      - checkout: self

      - task: UseJavaVersion@0
        inputs:
          versionSpec: '11'

      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          options: '-Xmx3072m'
          tasks: 'clean test'