name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: actions/setup-java@v2
      with:
       fetch-depth: 0
       distribution: 'temurin'
       java-version: '11'
    - run: ./gradlew clean test aggregate
    
    - name: Init new repo in dist folder and commit generated files
      run: |
       cd target/site/serenity/
       git init
       git add -A
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git commit -m 'deploy'
       
    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        exclude_assets: '.png,/bootstrap-treeview/dist/bootstrap-treeview.min.css,/bootstrap-treeview/dist/bootstrap-treeview.min.js'
        force: true
        directory: target/site/serenity/
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
          publish-dir: './target/site/serenity/'
          production-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
      env:
          NETLIFY_AUTH_TOKEN: 'wpS8NssRJlLZ4XPIbvMystfcFcvGh2xcJvv4SceNzDI'
          NETLIFY_SITE_ID: '5304aaad-9095-4092-9889-743e4ab360a9'
      timeout-minutes: 1
